package com.yyf.hap.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import org.hibernate.validator.constraints.Length;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "hap_inv_inventory_items")
public class InvInventoryItems extends BaseDTO {

     public static final String FIELD_INVENTORY_ITEM_ID = "inventoryItemId";
     public static final String FIELD_ITEM_CODE = "itemCode";
     public static final String FIELD_ITEM_UOM = "itemUom";
     public static final String FIELD_ITEM_DESCRIPTION = "itemDescription";
     public static final String FIELD_ORDER_FLAG = "orderFlag";
     public static final String FIELD_START_ACTIVE_DATE = "startActiveDate";
     public static final String FIELD_END_ACTIVE_DATE = "endActiveDate";
     public static final String FIELD_ENABLED_FLAG = "enabledFlag";


     @Id
     @GeneratedValue
     private Long inventoryItemId;

     @NotEmpty
     @Length(max = 60)
     private String itemCode;

     @NotEmpty
     @Length(max = 60)
     private String itemUom;

     @NotEmpty
     @Length(max = 240)
     private String itemDescription;

     @NotEmpty
     @Length(max = 1)
     private String orderFlag;

     private Date startActiveDate;

     private Date endActiveDate;

     @NotEmpty
     @Length(max = 1)
     private String enabledFlag;


     public void setInventoryItemId(Long inventoryItemId){
         this.inventoryItemId = inventoryItemId;
     }

     public Long getInventoryItemId(){
         return inventoryItemId;
     }

     public void setItemCode(String itemCode){
         this.itemCode = itemCode;
     }

     public String getItemCode(){
         return itemCode;
     }

     public void setItemUom(String itemUom){
         this.itemUom = itemUom;
     }

     public String getItemUom(){
         return itemUom;
     }

     public void setItemDescription(String itemDescription){
         this.itemDescription = itemDescription;
     }

     public String getItemDescription(){
         return itemDescription;
     }

     public void setOrderFlag(String orderFlag){
         this.orderFlag = orderFlag;
     }

     public String getOrderFlag(){
         return orderFlag;
     }

     public void setStartActiveDate(Date startActiveDate){
         this.startActiveDate = startActiveDate;
     }

     public Date getStartActiveDate(){
         return startActiveDate;
     }

     public void setEndActiveDate(Date endActiveDate){
         this.endActiveDate = endActiveDate;
     }

     public Date getEndActiveDate(){
         return endActiveDate;
     }

     public void setEnabledFlag(String enabledFlag){
         this.enabledFlag = enabledFlag;
     }

     public String getEnabledFlag(){
         return enabledFlag;
     }

     }
